# Generated by Django 4.2.20 on 2025-10-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
