# Generated by Django 4.2.20 on 2025-09-30 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for URLs", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="50 is MAX length of category name.",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Check valid the sub-category name.",
                                regex="(^[A-Za-z][A-Za-z0-9_]{1,50}$)",
                            ),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                        verbose_name="Category name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="50 is MAX length of name.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Check valid a name.",
                                regex="(^[A-Za-z][A-Za-z0-9_]{1,50}$)",
                            ),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                        verbose_name="Status name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
                "ordering": ("-name",),
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for URLs", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="100 is MAX length of sub-category name.",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Check valid the sub-category name.",
                                regex="(^[A-Za-z][A-Za-z0-9_]{1,100}$)",
                            ),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                        verbose_name="Subcategory name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="TypeFlowModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for URLs", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="50 is MAX length of name.",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Check valid a name.",
                                regex="(^[A-Za-z][A-Za-z0-9_]{1,50}$)",
                            ),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                        verbose_name="Name of type",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flow.categorymodel",
                        verbose_name="Category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flow.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                to="flow.subcategory",
                verbose_name="categories",
            ),
        ),
        migrations.CreateModel(
            name="ContentFlowsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for URLs", unique=True
                    ),
                ),
                (
                    "money",
                    models.PositiveIntegerField(
                        help_text="Sum from 1 before 300000",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MinValueValidator(300000),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(100),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Za-z][A-Za-z_ .,]{1,150}$)"
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_id",
                    models.ForeignKey(
                        help_text="Select status name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flow.statusmodel",
                        verbose_name="Status",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        help_text="Select type name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flow.typeflowmodel",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow",
                "verbose_name_plural": "Flow",
                "unique_together": {("slug",)},
            },
        ),
        migrations.AlterUniqueTogether(
            name="categorymodel",
            unique_together={("name",)},
        ),
    ]
