# Generated by Django 4.2.20 on 2025-09-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeflowmodel",
            name="subcategory",
        ),
    ]
