# Generated by Django 4.2.20 on 2025-09-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={
                "ordering": ["name"],
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
            },
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="subcategory_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="flow.subcategory",
                verbose_name="SubCategory",
            ),
        ),
    ]
