# Generated by Django 4.2.20 on 2025-09-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_remove_typeflowmodel_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeflowmodel",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="flow.subcategory",
            ),
            preserve_default=False,
        ),
    ]
