# Generated by Django 4.2.20 on 2025-09-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0002_alter_categorymodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
