# Generated by Django 4.2.20 on 2025-09-30 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0003_alter_categorymodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="name",
            field=models.CharField(
                help_text="50 is MAX length of category name.",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Check valid the sub-category name.",
                        regex="(^[A-Za-z][A-Za-z0-9_]{1,50}$)",
                    ),
                    django.core.validators.MaxLengthValidator(50),
                ],
                verbose_name="Category name",
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="subcategory_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="flow.subcategory",
                unique=True,
                verbose_name="SubCategory",
            ),
        ),
    ]
