# Generated by Django 4.2.20 on 2025-09-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0003_typeflowmodel_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeflowmodel",
            name="subcategory",
        ),
    ]
