# Generated by Django 4.2.20 on 2025-09-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0004_alter_categorymodel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeflowmodel",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryname",
                to="flow.categorymodel",
                unique=True,
                verbose_name="Category",
            ),
        ),
    ]
