# Generated by Django 4.2.20 on 2025-09-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_typeflowmodel_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeflowmodel",
            name="subcategory",
        ),
    ]
