# Generated by Django 4.2.20 on 2025-09-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_alter_typeflowmodel_category_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentflowsmodel",
            options={"verbose_name": "Flow", "verbose_name_plural": "Flow"},
        ),
        migrations.AlterUniqueTogether(
            name="categorymodel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="typeflowmodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contentflowsmodel",
            name="slug",
            field=models.SlugField(
                default=1, help_text="Unique identifier for URLs", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="typeflowmodel",
            name="slug",
            field=models.SlugField(
                default=1, help_text="Unique identifier for URLs", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="subcategory_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="flow.subcategory",
                verbose_name="SubCategory",
            ),
        ),
        migrations.AlterField(
            model_name="typeflowmodel",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryname",
                to="flow.categorymodel",
                verbose_name="Category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categorymodel",
            unique_together={("name", "subcategory_id")},
        ),
        migrations.AlterUniqueTogether(
            name="contentflowsmodel",
            unique_together={("slug",)},
        ),
        migrations.AlterUniqueTogether(
            name="typeflowmodel",
            unique_together={("name", "category_id")},
        ),
    ]
