# Generated by Django 4.2.20 on 2025-09-30 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_remove_typeflowmodel_subcategory"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="typeflowmodel",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="typeflowmodel",
            name="name",
            field=models.CharField(
                help_text="50 is MAX length of name.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Check valid a name.",
                        regex="(^[A-Za-z][A-Za-z0-9-_]{1,50}$)",
                    ),
                    django.core.validators.MaxLengthValidator(50),
                ],
                verbose_name="Name of type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typeflowmodel",
            unique_together={("name", "category")},
        ),
    ]
