# Generated by Django 4.2.20 on 2025-09-30 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_alter_contentflowsmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="name",
            field=models.CharField(
                help_text="50 is MAX length of category name.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Check valid the sub-category name.",
                        regex="(^[A-Za-z][A-Za-z0-9_]{1,50}$)",
                    ),
                    django.core.validators.MaxLengthValidator(50),
                ],
                verbose_name="Category name",
            ),
        ),
    ]
