# Generated by Django 4.2.20 on 2025-09-30 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0007_alter_categorymodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeflowmodel",
            name="name",
            field=models.CharField(
                help_text="50 is MAX length of name.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Check valid a name.",
                        regex="(^[A-Za-z][A-Za-z0-9_]{1,50}$)",
                    ),
                    django.core.validators.MaxLengthValidator(50),
                ],
                verbose_name="Name of type",
            ),
        ),
    ]
