# Generated by Django 4.2.20 on 2025-09-30 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0007_alter_typeflowmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="money",
            field=models.PositiveIntegerField(
                help_text="Sum from 1 before 300000",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
