# Generated by Django 4.2.20 on 2025-09-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0008_alter_typeflowmodel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        through="flow.ContentFlowsModel", to="flow.statusmodel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentflowsmodel",
            name="article",
            field=models.ForeignKey(
                default=1,
                help_text="Select status name",
                on_delete=django.db.models.deletion.CASCADE,
                to="flow.article",
                verbose_name="Status",
            ),
            preserve_default=False,
        ),
    ]
