# Generated by Django 4.2.20 on 2025-10-01 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0009_alter_contentflowsmodel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 1, 8, 22, 38, 95571),
                verbose_name="Date of creation",
            ),
        ),
    ]
