# Generated by Django 4.2.20 on 2025-09-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0009_article_contentflowsmodel_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentflowsmodel",
            name="article",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
