# Generated by Django 4.2.20 on 2025-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0010_remove_contentflowsmodel_article_delete_article"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categorymodel",
            unique_together={("name",)},
        ),
        migrations.RemoveField(
            model_name="categorymodel",
            name="subcategory_id",
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="subcategory_id",
            field=models.ManyToManyField(to="flow.subcategory"),
        ),
    ]
