# Generated by Django 4.2.20 on 2025-10-01 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0010_alter_contentflowsmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Date of creation"
            ),
        ),
    ]
