# Generated by Django 4.2.20 on 2025-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0011_alter_categorymodel_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="subcategory_id",
            field=models.ManyToManyField(
                related_name="subcategories", to="flow.subcategory"
            ),
        ),
    ]
