# Generated by Django 4.2.20 on 2025-10-01 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0011_alter_contentflowsmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Date of creation",
            ),
        ),
    ]
