# Generated by Django 4.2.20 on 2025-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0012_alter_contentflowsmodel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
