# Generated by Django 4.2.20 on 2025-09-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0013_categorysubcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymodel",
            name="subcategory_id",
        ),
        migrations.AlterField(
            model_name="typeflowmodel",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryname",
                to="flow.categorysubcategory",
                verbose_name="Category",
            ),
        ),
    ]
