# Generated by Django 4.2.20 on 2025-10-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0014_sitespecificsocialmediasettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSpecificSocialMediaSettings",
        ),
    ]
