# Generated by Django 4.2.20 on 2025-09-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0014_remove_categorymodel_subcategory_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorysubcategory",
            name="subcategory",
        ),
    ]
