# Generated by Django 4.2.20 on 2025-10-04 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0015_delete_sitespecificsocialmediasettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
