# Generated by Django 4.2.20 on 2025-09-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0015_remove_categorysubcategory_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="subcategory_list",
            field=models.ManyToManyField(blank=True, to="flow.subcategory"),
        ),
    ]
