# Generated by Django 4.2.20 on 2025-09-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0016_categorymodel_subcategory_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorysubcategory",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Subcategory",
                to="flow.subcategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorysubcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Category",
                to="flow.categorymodel",
            ),
        ),
    ]
