# Generated by Django 4.2.20 on 2025-10-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0016_alter_contentflowsmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeflowmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="flow.categorymodel",
                unique=True,
                verbose_name="Category",
            ),
        ),
    ]
