# Generated by Django 4.2.20 on 2025-09-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0017_categorysubcategory_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymodel",
            name="subcategory_list",
        ),
        migrations.RemoveField(
            model_name="categorysubcategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="categorysubcategory",
            name="subcategory",
        ),
    ]
