# Generated by Django 4.2.20 on 2025-10-05 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0017_alter_typeflowmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentflowsmodel",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(100),
                    django.core.validators.RegexValidator(
                        regex="(^[A-Za-z][A-Za-z_ .,]{1,150}$)"
                    ),
                ],
                verbose_name="Comments",
            ),
        ),
    ]
