# Generated by Django 4.2.20 on 2025-09-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0018_remove_categorymodel_subcategory_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="subcategory_list",
            field=models.ManyToManyField(blank=True, to="flow.subcategory"),
        ),
        migrations.AddField(
            model_name="typeflowmodel",
            name="subcategory_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Category",
                to="flow.subcategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="typeflowmodel",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Category",
                to="flow.categorymodel",
            ),
        ),
        migrations.DeleteModel(
            name="CategorySubcategory",
        ),
    ]
