# Generated by Django 4.2.20 on 2025-09-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0019_categorymodel_subcategory_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymodel",
            name="subcategory_list",
        ),
        migrations.RemoveField(
            model_name="typeflowmodel",
            name="subcategory_id",
        ),
    ]
